# Generated by Django 2.2 on 2020-08-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=512)),
                ('dimension', models.CharField(max_length=128)),
                ('weight', models.FloatField(default=0)),
                ('value', models.FloatField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
