# Generated by Django 2.2 on 2020-08-30 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='trip_accepted_at',
        ),
    ]
