# Generated by Django 2.2 on 2020-08-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_remove_trip_trip_accepted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_accepted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
