# Generated by Django 2.2 on 2020-09-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_trip_trip_accepted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_json_request',
            field=models.TextField(blank=True, null=True),
        ),
    ]
